#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: klearUsersRolesList_screen
  screens: 
    klearUsersRolesList_screen: &klearUsersRolesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *KlearUsersRoles
      title: _("List of %s %2s", ngettext('Klear users role', 'Klear users roles', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            klearUsersRolesEdit_screen: true
          dialogs: 
            klearUsersRolesDel_dialog: true
          default: klearUsersRolesEdit_screen
      options: 
        title: _("Options")
        screens: 
          klearUsersRolesNew_screen: true
        dialogs: 
          klearUsersRolesDel_dialog: true
    klearUsersRolesNew_screen: &klearUsersRolesNew_screenLink 
      <<: *KlearUsersRoles
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Klear users role', 'Klear users roles', 1))
      shortcutOption: N
    klearUsersRolesEdit_screen: &klearUsersRolesEdit_screenLink 
      <<: *KlearUsersRoles
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Klear users role', 'Klear users roles', 1), "[format| (%item%)]")
  dialogs: 
    klearUsersRolesDel_dialog: &klearUsersRolesDel_dialogLink 
      <<: *KlearUsersRoles
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Klear users role', 'Klear users roles', 1))
      description: _("Do you want to delete this %s?", ngettext('Klear users role', 'Klear users roles', 1))
      message: _("%s successfully deleted.", ngettext('Klear users role', 'Klear users roles', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
