#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: klearRolesList_screen
  screens: 
    klearRolesList_screen: &klearRolesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *KlearRoles
      title: _("List of %s %2s", ngettext('Klear role', 'Klear roles', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            klearRolesEdit_screen: true
          dialogs: 
            klearRolesDel_dialog: true
          default: klearRolesEdit_screen
      options: 
        title: _("Options")
        screens: 
          klearRolesNew_screen: true
        dialogs: 
          klearRolesDel_dialog: true
    klearRolesNew_screen: &klearRolesNew_screenLink 
      <<: *KlearRoles
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Klear role', 'Klear roles', 1))
      shortcutOption: N
    klearRolesEdit_screen: &klearRolesEdit_screenLink 
      <<: *KlearRoles
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Klear role', 'Klear roles', 1), "[format| (%item%)]")
  dialogs: 
    klearRolesDel_dialog: &klearRolesDel_dialogLink 
      <<: *KlearRoles
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Klear role', 'Klear roles', 1))
      description: _("Do you want to delete this %s?", ngettext('Klear role', 'Klear roles', 1))
      message: _("%s successfully deleted.", ngettext('Klear role', 'Klear roles', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
