#!/bin/bash

if [[ $0 == /* ]]; then
    BASEDIR=`dirname $0`       # Absolute
else
    BASEDIR=`dirname $PWD/$0`  # Relative
fi

/usr/bin/php ${BASEDIR}/../web/vendor/bin/phing $1 -De=development -Dk=../web/vendor/ -Da=../web/application