#!/bin/bash

if [[ $0 == /* ]]; then
    BASEDIR=`dirname $0`       # Absolute
else
    BASEDIR=`dirname $PWD/$0`  # Relative
fi

/usr/bin/php ${BASEDIR}/../web/vendor/phing/phing/bin/phing.php migrate -De=production -Dk=/opt/klear -Da=../web/application