<title>Zend</title>

<!-- Charset usado en la web -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="Content-Type" content="text/html; charset=UTF-8" />

<!-- Geolocalización -->
<meta name="geo.country"   content="" />
<meta name="geo.placename" content="" />
<meta name="geo.position"  content="" />

<!-- Idioma Principal -->
<meta http-equiv="language" content="spanish" />
<meta http-equiv="content-language" content="es-es" />
<meta property="og:locale" content="es_ES" />

<!-- Metas de información general -->
<meta name="title"       content="" />
<meta name="keywords"    content="" />
<meta name="description" content="" />

<!-- Metas para Google/Facebook -->
<!-- Nombre de la Web -->
<meta property="og:site_name"   content="" />
<meta property="og:title"       content="" />
<meta property="og:description" content="" />

<!-- Url Actial -->
<meta property="og:url"         content="" />

<!-- type = article/website/blog/product -->
<meta property="og:type"        content="" />

<!-- Facebook: Standards vary, but an image at least 200x200px works best. Facebook recommends large images up to 1200x630px wide. -->
<meta property="og:image"        content="" />
<meta property="og:image:type"   content="" />
<meta property="og:image:width"  content="1200" />
<meta property="og:image:height" content="630" />

<!-- url g+ website -->
<link href="" rel="publisher" />


<!-- Metas para Twitter -->
<!--  title:       maximo 70 caracteres  -->
<!--  description: maximo 200 caracteres  -->
<!--  image: imagenes de 1MB  -->

<!-- cuenta de portal @web -->
<meta name="twitter:site" content="" />

<!-- Url actual -->
<meta name="twitter:url"         content="" />
<meta name="twitter:title"       content="" />
<meta name="twitter:description" content="" />

<!-- Para que los navegadores adapten el contenido -->
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />

<!-- Iconografias de la Web -->

<!-- Favicon 48x48 -->
<link rel="shortcut icon" href="/favicon.ico" />

<!-- desde android 5 en adelante, se le puede dar un color a la barra del navegador. -->
<meta name="theme-color" content="#000" />

<!-- Imagenes para mejor resolución del favicon (Chrome/FireFox), icono de favorito y acceso directo en dispositivos móviles. -->
<link rel="icon" sizes="128x128" href="" />
<link rel="icon" sizes="192x192" href="" />

<!-- Apple -->
<!-- Imagenes para mejor resolución del favicon, icono de favorito  y acceso directo en dispositivos móviles. -->
<!-- iPhone & iPod Touch (Non-Retina) -->
<link rel="apple-touch-icon" sizes="60x60" href="" />
<!-- iPad 2 & iPad mini (Non-Retina) -->
<link rel="apple-touch-icon" sizes="76x76" href="" />
<!-- Phone & iPod Touch (Retina) -->
<link rel="apple-touch-icon" sizes="120x120" href="" />
<!-- iPad & iPad mini (Retina) -->
<link rel="apple-touch-icon" sizes="152x152" href="" />

<!-- Por defecto 57x57 -->
<link rel="apple-touch-icon-precomposed" href="">

<!-- Soporte general por si no detecto los optimos -->
<link rel="apple-touch-icon-precomposed" sizes="72x72"   href="" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="" />

<!-- Bootstrap -->
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
