production: 
  class: \{appnamespace}\Model\KlearRoles
  fields: 
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      default: true
    description: 
      title: ngettext('Description', 'Descriptions', 1)
      type: text
      defaultValue: 
    identifier: 
      title: ngettext('Identifier', 'Identifiers', 1)
      type: text
      required: true
    KlearRolesSections:
      title: _("Secciones asociadas")
      type: multiselect
      source:
        data: mapper
        config:
          relationMapper: \{appnamespace}\Mapper\Sql\KlearRolesSections
          relationProperty: KlearSection
          relatedMapperName: \{appnamespace}\Mapper\Sql\KlearSections
          relatedFieldName: name
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
